### ISSUE TITLE
A bit of housekeeping, and get this on hackage.

### ISSUE THREAD

**Issue by zenhack** [zenhack/haskell-quota#1]
This library hasn't changed much lately, and it would be nice if builds for haskell-capnp could just pull it from hackage like everything else. We should go through, add docs, sanity check things, and then upload it.

**Comment by zenhack** [comment]
I added a bunch of docs, and I'm more-or-less comfy with this now, though there are a few bits of the API that seem maybe a bit weird to me still.

@taktoa, wouldn't mind your opinion on the state of the library.

**Comment by taktoa** [comment]
sorry, I've been a bit busy with my family the last few days; I fly back on Tuesday night so after that I can find some time to review the library

**Comment by zenhack** [comment]
Going to close this one. The functionality from this package ended up being folded into haskell-capnp itself, and so this package isn't really used anymore:

http://hackage.haskell.org/package/capnp-0.3.0.0/docs/Data-Capnp-TraversalLimit.html

I'll also update the readme to reflect the current status of this package.
